# Generated by Django 4.0.4 on 2022-07-19 07:19

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Yuridik shaxs arizalari',
            },
        ),
        migrations.CreateModel(
            name='IndividualRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Jismoniy shaxs arizalari',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=backend.models.generate_key, max_length=16),
        ),
    ]
