# Generated by Django 4.0.4 on 2022-07-19 07:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_entityrequest_individualrequest_user_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityRequest',
        ),
        migrations.DeleteModel(
            name='IndividualRequest',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('users', django.contrib.auth.models.UserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
