# Generated by Django 4.0.4 on 2022-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_individualrequest_entityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individualrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
