# Generated by Django 4.0.3 on 2022-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_entityrequest_paid_individualrequest_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityrequest',
            options={'verbose_name': 'Yuridik shaxs arizasi', 'verbose_name_plural': 'Yuridik shaxs arizalari'},
        ),
        migrations.AlterModelOptions(
            name='individualrequest',
            options={'verbose_name': 'Jismoniy shaxs arizasi', 'verbose_name_plural': 'Jismoniy shaxs arizalari'},
        ),
        migrations.AddField(
            model_name='entityrequest',
            name='created_workplace',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityrequest',
            name='debt_value',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityrequest',
            name='proposition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityrequest',
            name='term',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualrequest',
            name='created_workplace',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualrequest',
            name='debt_value',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualrequest',
            name='proposition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualrequest',
            name='term',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
