# Generated by Django 4.0.4 on 2022-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_payment_entity_request_payment_individual_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualrequest',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
