# Generated by Django 4.0.4 on 2022-09-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_individualrequest_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
